### ISSUE TITLE
Add more realistic display of fretboard

### ISSUE THREAD

**Issue by heczis** [juhyxx/scalear#2]
- Non-uniform distance between frets.
- Circles that indicate note positions aligned to frets instead of the middle of the field between frets:

![drawing](https://cloud.githubusercontent.com/assets/9701146/5611546/351ebaea-94c8-11e4-8c62-3bdac1391a82.png)

Can be made optional, e.g. using a checkbox.

**Comment by juhyxx** [comment]
Non-uniform distance is not so good idea - it decrease readiblity.
